// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import("@arco-design/web-vue")["Button"];
    ACheckbox: typeof import("@arco-design/web-vue")["Checkbox"];
    ACol: typeof import('@arco-design/web-vue')['Col']
    AForm: typeof import("@arco-design/web-vue")["Form"];
    AFormItem: typeof import("@arco-design/web-vue")["FormItem"];
    AInput: typeof import("@arco-design/web-vue")["Input"];
    AInputPassword: typeof import("@arco-design/web-vue")["InputPassword"];
    ARow: typeof import('@arco-design/web-vue')['Row']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfoDescription: typeof import('./src/components/InfoDescription/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Weather: typeof import('./src/components/weather/Weather.vue')['default']
  }
}

export {}
